app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  link:
    length: 7
    default-expiration-days: 30
  ip-api:
    enabled: true
    url: http://ip-api.com/json/
    timeout-ms: 2000
    batch-size: 100

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/url_shortener}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:your_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8080

logging:
  level:
    ru.hastg99.urlshortener: DEBUG